# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True or False

SLEEP_FROM = 500  # Second
SLEEP_TO = 1000  # Second

QUANTITY_THREADS = 1

THREAD_SLEEP_FROM = 5
THREAD_SLEEP_TO = 5

# PROXY MODE
USE_PROXY = False

# GWEI CONTROL MODE
CHECK_GWEI = True  # True or False
MAX_GWEI = 25

GAS_MULTIPLIER = 1.3

# RETRY MODE
RETRY_COUNT = 3

# INCH API KEY
INCH_API_KEY = ""
