# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True or False

QUANTITY_RUN_ACCOUNTS = 5

SLEEP_FROM = 500  # Second
SLEEP_TO = 1000  # Second

# PROXY MODE
USE_PROXY = False

# GWEI CONTROL MODE
CHECK_GWEI = True  # True or False
MAX_GWEI = 25

GAS_MULTIPLIER = 1.3

# RETRY MODE
RETRY_COUNT = 3

# INCH API KEY
INCH_API_KEY = ""
